/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#343d96",
        "surface-container-low": "#fbf5c1",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f8f3be",
        outline: "#837563",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bdc2ff",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffd9e1",
        "on-primary-fixed": "#291800",
        "tertiary-fixed-dim": "#ffb1c5",
        surface: "#fffadf",
        "on-secondary-fixed": "#000767",
        "tertiary-container": "#ffafc4",
        "surface-container-high": "#f0eab6",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffddb3",
        "surface-bright": "#fffadf",
        "on-surface": "#1e1c00",
        "primary-fixed-dim": "#ffb951",
        "on-primary-container": "#714a00",
        secondary: "#4c56af",
        "on-primary-fixed-variant": "#633f00",
        "outline-variant": "#d6c4b0",
        "on-tertiary-fixed": "#3f001b",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb951",
        "surface-variant": "#eae4b1",
        "surface-dim": "#e1dca9",
        primary: "#825500",
        "on-tertiary-container": "#9a1d50",
        "surface-container": "#f6f0bb",
        "on-secondary-container": "#27308a",
        tertiary: "#ab2c5d",
        "surface-container-highest": "#eae4b1",
        "primary-container": "#ffb84d",
        "surface-tint": "#825500",
        "on-tertiary-fixed-variant": "#8b0e45",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#514536",
        "on-background": "#1e1c00",
        background: "#fffadf",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e0e0ff",
        "inverse-surface": "#34310d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
        "max-width": "1280px",
      },
      fontFamily: {
        "label-caps": [
          "Space Grotesk",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "headline-lg-mobile": [
          "Anton",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "headline-lg": ["Anton", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["Work Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-md": [
          "Space Grotesk",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "display-lg": ["Anton", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Work Sans", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "36px",
          { lineHeight: "42px", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "0.05em", fontWeight: "400" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": [
          "80px",
          { lineHeight: "90px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
};
